Mention loaders that can handle hot reloading
webpack-contrib/extract-text-webpack-plugin pull request #680
Opened 2017-12-09 19:45 UTC by sheerun

Disclaimer: I'm an author of extracted-loader

2017-12-09 19:58 UTC, sheerun commented
And by the way, I'd be happy if you decided to incorporate extracted-loader into extract-text-webpack-plugin behind a flag (e.g. `hotreload=true`)

2018-02-01 10:04 UTC, evilebottnawi commented
@sheerun Thanks for PR. Feel free to PR. It would be great if `extract-text-webpack-plugin` will be support hot reload. I think we should this support without option, just out of box.

2018-02-02 06:43 UTC, sheerun commented
This might be a breaking change for some people if they already use some kind of hot reloading solution. Are you sure you want patch change without any flag?

2018-02-02 10:07 UTC, evilebottnawi commented
@sheerun This PR is patch, new PR with support hot reloading will have other label :+1: PR welcome

2018-02-28 04:10 UTC, michael-ciniawsky requested changes

2018-02-28 04:10 UTC, michael-ciniawsky commented on README.md
> +The [extraced-loader](https://github.com/sheerun/extracted-loader) or [css-hot-reloader](https://github.com/shepherdwind/css-hot-loader) might be helpful.
`### Hot reloading`  => ```### `HMR` ```

```diff
- css-hot-reloader
+ css-hot-loader
```

2019-05-29 11:49 UTC, evilebottnawi commented
DEPRECATED
Please use: https://github.com/webpack-contrib/mini-css-extract-plugin

2019-05-29 11:49 UTC, closed without merging